[project]
name = 'hiro-hacks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bootstrap]
path = 'contracts/bootstrap.clar'
clarity_version = 2
epoch = 2.1

[contracts.core]
path = 'contracts/core.clar'
clarity_version = 2
epoch = 2.1

[contracts.extension-trait]
path = 'contracts/extension-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.hello-world]
path = 'contracts/hello-world.clar'
clarity_version = 2
epoch = 2.1

[contracts.membership-token]
path = 'contracts/membership-token.clar'
clarity_version = 2
epoch = 2.1

[contracts.milestone-extension]
path = 'contracts/milestone-extension.clar'
clarity_version = 2
epoch = 2.1

[contracts.milestone-extension-proposal]
path = 'contracts/milestone-extension-proposal.clar'
clarity_version = 2
epoch = 2.1

[contracts.proposal-submission]
path = 'contracts/proposal-submission.clar'
clarity_version = 2
epoch = 2.1

[contracts.proposal-trait]
path = 'contracts/proposal-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.proposal-voting]
path = 'contracts/proposal-voting.clar'
clarity_version = 2
epoch = 2.1

[contracts.treasury]
path = 'contracts/treasury.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
